#!/usr/bin/env python3
# Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.
#
# SPDX-License-Identifier: MIT

# MIT License
#
# Copyright (c) 2023-2025 Advanced Micro Devices, Inc. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""
Generate CPU vs GPU profiling comparison report from analyze_stages.py output.

Reads two analysis.json files (CPU-only and GPU-enabled) and produces:
  - A formatted text comparison on stdout (always)
  - Matplotlib graphs (.png) when --output-dir is given
  - A Markdown report (PROFILING_REPORT.md) when --output-dir is given

Arguments:
  cpu_analysis    Path to CPU-only analysis.json
  gpu_analysis    Path to GPU analysis.json
  --output-dir    Directory for graphs and Markdown report (optional)

Prerequisites:
  - Two analysis.json files generated by analyze_stages.py
  - matplotlib (pip install matplotlib) for graph/report generation

Usage:
    # Text-only comparison (stdout):
    python3 generate_profiling_report.py cpu/analysis.json gpu/analysis.json

    # Full report with graphs and Markdown:
    python3 generate_profiling_report.py cpu/analysis.json gpu/analysis.json \\
        --output-dir ./minimap2_profiling/report
"""

import argparse
import json
import os
import shutil
import sys
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from stage_defs import PIPELINE_STAGES, reclassify_gpu_chain, shorten_kernel_name

# ── Stages used for graphs and Markdown tables ─────────────────────────────
GRAPH_STAGES = ['seeding', 'chaining', 'alignment']
STAGE_COLORS = {
    'seeding': '#2196F3', 'chaining': '#FF9800', 'alignment': '#4CAF50',
    'io': '#9C27B0', 'gpu_other': '#607D8B', 'other': '#9E9E9E',
}


# ═══════════════════════════════════════════════════════════════════════════
# Formatting helpers
# ═══════════════════════════════════════════════════════════════════════════

def format_duration(us: float) -> str:
    """Format duration in human-readable form."""
    if us == 0:
        return "-"
    if abs(us) < 1000:
        return f"{us:.2f}µs"
    elif abs(us) < 1_000_000:
        return f"{us/1000:.2f}ms"
    else:
        return f"{us/1_000_000:.2f}s"


def _fmt_bytes(b: int) -> str:
    """Format byte count in human-readable form."""
    if b >= 1 << 30:
        return f"{b / (1 << 30):.2f} GiB"
    if b >= 1 << 20:
        return f"{b / (1 << 20):.2f} MiB"
    if b >= 1 << 10:
        return f"{b / (1 << 10):.2f} KiB"
    return f"{b} B"


def _fmt_s(us: float) -> str:
    """Short-form formatter for Markdown tables."""
    if us >= 1e6:
        return f"{us / 1e6:.2f}s"
    if us >= 1e3:
        return f"{us / 1e3:.1f}ms"
    return f"{us:.0f}µs"


# ═══════════════════════════════════════════════════════════════════════════
# Data loading / extraction
# ═══════════════════════════════════════════════════════════════════════════

def load_analysis(path: Path) -> dict:
    """Load analysis.json file."""
    with open(path) as f:
        return json.load(f)


def extract_trace_functions(data: dict) -> Dict[str, dict]:
    """Extract all trace functions from analysis data."""
    funcs = {}
    for stage, sdata in data.get('stages', {}).items():
        for func in sdata.get('trace_functions', []):
            name = func.get('name', '')
            if name:
                if name not in funcs:
                    funcs[name] = {
                        'time_us': 0,
                        'count': 0,
                        'file': func.get('file', ''),
                        'stage': stage,
                        '_stage_time': {},
                    }
                funcs[name]['time_us'] += func.get('duration_us', 0)
                funcs[name]['count'] += func.get('count', 0)
                st = funcs[name]['_stage_time']
                st[stage] = st.get(stage, 0) + func.get('duration_us', 0)
    for info in funcs.values():
        st = info.pop('_stage_time')
        if st:
            info['stage'] = max(st, key=st.get)
    return funcs


def extract_gpu_kernels(data: dict) -> Dict[str, dict]:
    """Extract all GPU kernels from analysis data."""
    kernels = {}
    for stage, sdata in data.get('stages', {}).items():
        for kernel in sdata.get('gpu_kernels', []):
            name = kernel.get('name', '')
            if name:
                short_name = shorten_kernel_name(name)
                if short_name not in kernels:
                    kernels[short_name] = {
                        'full_name': name,
                        'time_us': 0,
                        'count': 0,
                        'stage': stage,
                    }
                kernels[short_name]['time_us'] += kernel.get('duration_us', 0)
                kernels[short_name]['count'] += kernel.get('count', 0)
    return kernels


def extract_kernel_counters(data: dict) -> Dict[str, dict]:
    """Extract kernel hardware counter data from analysis data."""
    raw = data.get('kernel_counters', {})
    if not raw:
        return {}
    counters = {}
    for name, info in raw.items():
        short = shorten_kernel_name(name)
        existing = counters.get(short)
        if existing is None or info.get('dispatch_count', 0) > existing.get('dispatch_count', 0):
            counters[short] = info
    return counters


def extract_gpu_api_calls(data: dict) -> Dict[str, dict]:
    """Extract all GPU API calls (HIP/HSA) across stages."""
    calls: Dict[str, dict] = {}
    for stage, sdata in data.get('stages', {}).items():
        for call in sdata.get('gpu_api_calls', []):
            name = call.get('name', '')
            if not name:
                continue
            if name not in calls:
                calls[name] = {'time_us': 0, 'count': 0, 'bytes_total': 0, 'stage': stage}
            calls[name]['time_us'] += call.get('duration_us', 0)
            calls[name]['count'] += call.get('count', 0)
            calls[name]['bytes_total'] += call.get('bytes_total', 0)
    return calls


def extract_transfers(api_calls: Dict[str, dict]) -> Dict[str, dict]:
    """Filter API calls to Host<->Device memory copy operations."""
    return {n: v for n, v in api_calls.items() if 'memcpy' in n.lower()}


def analyze_sync_overlap(gpu_api_calls: Dict[str, dict],
                        gpu_kernels: Dict[str, dict],
                        gpu_kernel_total_us: float) -> Optional[Dict[str, Any]]:
    """Detect whether hipDeviceSynchronize time overlaps with kernel execution.

    When kernels are launched asynchronously and each launch is followed by a
    sync call, the sync duration equals the kernel duration (it's just waiting).
    This function identifies that pattern and computes the real non-overlapping
    HIP API overhead."""
    sync_info = gpu_api_calls.get('hipDeviceSynchronize')
    if not sync_info:
        return None

    sync_time_us = sync_info['time_us']
    sync_count = sync_info['count']

    # Total dispatched kernel count (all kernels including runtime internals)
    total_kernel_count = sum(k['count'] for k in gpu_kernels.values())
    # User-launched kernel count (from hipLaunchKernel API)
    launch_info = gpu_api_calls.get('hipLaunchKernel', {})
    user_kernel_count = launch_info.get('count', 0)

    # Detect sync pattern by comparing sync count with user kernel launches
    # (runtime-internal kernels like __amd_rocclr_copyBuffer are not user-launched)
    sync_matches_launches = (user_kernel_count > 0 and
                             abs(sync_count - user_kernel_count) / user_kernel_count < 0.05)
    # Also check if sync time ≈ kernel time (within 20% tolerance)
    sync_approx_kernel_time = (gpu_kernel_total_us > 0 and
                               abs(sync_time_us - gpu_kernel_total_us) / gpu_kernel_total_us < 0.20)

    is_sync_waiting = sync_matches_launches or sync_approx_kernel_time

    # The overlap is the portion of sync time that's just waiting for kernels
    overlap_us = min(sync_time_us, gpu_kernel_total_us) if is_sync_waiting else 0
    sync_overhead_us = sync_time_us - overlap_us

    # Compute real (non-sync-wait) HIP API overhead
    all_hip_time_us = sum(v['time_us'] for n, v in gpu_api_calls.items()
                         if n.startswith('hip'))
    real_api_overhead_us = all_hip_time_us - overlap_us

    # Categorize HIP API calls
    alloc_time = sum(v['time_us'] for n, v in gpu_api_calls.items()
                     if n in ('hipMalloc', 'hipFree', 'hipHostMalloc', 'hipHostFree'))
    alloc_count = sum(v['count'] for n, v in gpu_api_calls.items()
                      if n in ('hipMalloc', 'hipFree', 'hipHostMalloc', 'hipHostFree'))
    # Only count HIP API-level memcpy calls (hip*), not hardware DMA entries (memcpy_*)
    memcpy_time = sum(v['time_us'] for n, v in gpu_api_calls.items()
                      if 'memcpy' in n.lower() and n.startswith('hip'))
    memcpy_count = sum(v['count'] for n, v in gpu_api_calls.items()
                       if 'memcpy' in n.lower() and n.startswith('hip'))
    launch_time = sum(v['time_us'] for n, v in gpu_api_calls.items()
                      if 'launch' in n.lower() or 'push' in n.lower() or 'pop' in n.lower())
    memset_time = sum(v['time_us'] for n, v in gpu_api_calls.items()
                      if 'memset' in n.lower())

    # Find which kernel the syncs are likely waiting for
    dominant_kernel = max(gpu_kernels.items(), key=lambda x: x[1]['time_us']) if gpu_kernels else None

    return {
        'sync_time_us': sync_time_us,
        'sync_count': sync_count,
        'kernel_count': total_kernel_count,
        'user_kernel_count': user_kernel_count,
        'is_sync_waiting': is_sync_waiting,
        'sync_matches_launches': sync_matches_launches,
        'sync_approx_kernel_time': sync_approx_kernel_time,
        'overlap_us': overlap_us,
        'sync_overhead_us': sync_overhead_us,
        'all_hip_time_us': all_hip_time_us,
        'real_api_overhead_us': real_api_overhead_us,
        'alloc_time_us': alloc_time,
        'alloc_count': alloc_count,
        'memcpy_time_us': memcpy_time,
        'memcpy_count': memcpy_count,
        'launch_time_us': launch_time,
        'memset_time_us': memset_time,
        'dominant_kernel': (dominant_kernel[0], dominant_kernel[1]['time_us'],
                           dominant_kernel[1]['count']) if dominant_kernel else None,
    }


# ═══════════════════════════════════════════════════════════════════════════
# Text report (stdout)
# ═══════════════════════════════════════════════════════════════════════════

def print_comparison(cpu_data: dict, gpu_data: dict,
                     cpu_path: Path, gpu_path: Path):
    """Print formatted text comparison report to stdout."""
    cpu_funcs = extract_trace_functions(cpu_data)
    gpu_funcs = extract_trace_functions(gpu_data)
    gpu_kernels = extract_gpu_kernels(gpu_data)
    gpu_counters = extract_kernel_counters(gpu_data)
    gpu_api_calls = extract_gpu_api_calls(gpu_data)

    # Reclassify gpu_chain_* functions to chaining stage
    for name, info in gpu_funcs.items():
        info['stage'] = reclassify_gpu_chain(name, info.get('stage', ''))

    cpu_summary = cpu_data.get('summary', {})
    gpu_summary = gpu_data.get('summary', {})
    cpu_total = cpu_summary.get('total_trace_time_us', 0)
    gpu_total = gpu_summary.get('total_trace_time_us', 0)
    gpu_kernel_total = gpu_summary.get('total_gpu_time_us', 0)

    # Header
    print("=" * 100)
    print("MINIMAP2 CPU vs GPU PROFILING COMPARISON")
    print("=" * 100)
    print(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"CPU Analysis: {cpu_path}")
    print(f"GPU Analysis: {gpu_path}")
    print()

    # ── Section 1: Overall Summary ──────────────────────────────────────
    print("=" * 100)
    print("SECTION 1: OVERALL SUMMARY")
    print("=" * 100)
    print()
    print(f"{'Metric':<40} {'CPU Mode':>20} {'GPU Mode':>20} {'Difference':>15}")
    print("-" * 100)
    print(f"{'Total Trace Time':<40} {format_duration(cpu_total):>20} {format_duration(gpu_total):>20} {format_duration(cpu_total - gpu_total):>15}")
    print(f"{'GPU Kernel Time':<40} {'-':>20} {format_duration(gpu_kernel_total):>20} {'-':>15}")

    if gpu_total > 0:
        speedup = cpu_total / gpu_total
        if speedup >= 1:
            print(f"{'Overall Speedup':<40} {'-':>20} {'-':>20} {speedup:>14.2f}x")
        else:
            print(f"{'Overall Slowdown':<40} {'-':>20} {'-':>20} {1/speedup:>14.2f}x")
    print()

    # Per-stage summary
    print("Per-Stage Timing:")
    print(f"{'Stage':<16} {'CPU Time':>12} {'%CPU':>6} {'GPU Time':>12} {'%GPU':>6} {'GPU Kernel':>12} {'Speedup':>8}")
    print("-" * 78)

    stage_rows = []
    for stage in PIPELINE_STAGES:
        cpu_stage = cpu_data.get('stages', {}).get(stage, {})
        gpu_stage = gpu_data.get('stages', {}).get(stage, {})
        cpu_time = cpu_stage.get('trace_time_us', 0)
        gpu_time = gpu_stage.get('trace_time_us', 0)
        gpu_kernel = gpu_stage.get('gpu_time_us', 0)

        if cpu_time == 0 and gpu_time == 0:
            continue

        speedup = cpu_time / gpu_time if gpu_time > 0 else 0
        speedup_str = f"{speedup:.2f}x" if speedup > 0 else "-"
        cpu_pct = cpu_time / cpu_total * 100 if cpu_total > 0 else 0
        gpu_pct = gpu_time / gpu_total * 100 if gpu_total > 0 else 0

        stage_rows.append((stage, cpu_time, cpu_pct, gpu_time, gpu_pct, gpu_kernel, speedup, speedup_str))
        print(f"{stage.upper():<16} {format_duration(cpu_time):>12} {cpu_pct:>5.1f}% {format_duration(gpu_time):>12} {gpu_pct:>5.1f}% {format_duration(gpu_kernel):>12} {speedup_str:>8}")
    print()

    # GPU Memory Usage
    cpu_mem = cpu_summary.get('gpu_memory', {})
    gpu_mem = gpu_summary.get('gpu_memory', {})
    if cpu_mem or gpu_mem:
        cpu_tracking = cpu_mem.get('tracking', 'n/a')
        gpu_tracking = gpu_mem.get('tracking', 'n/a')
        print(f"GPU Memory (VRAM via rocm-smi, tracking: cpu={cpu_tracking}, gpu={gpu_tracking}):")
        print(f"{'Metric':<40} {'CPU Mode':>20} {'GPU Mode':>20}")
        print("-" * 82)
        for label, key in [('VRAM Baseline', 'vram_baseline_bytes'),
                           ('VRAM Peak', 'vram_peak_bytes'),
                           ('VRAM Delta (peak - baseline)', 'vram_delta_bytes')]:
            cpu_val = _fmt_bytes(cpu_mem[key]) if key in cpu_mem else '-'
            gpu_val = _fmt_bytes(gpu_mem[key]) if key in gpu_mem else '-'
            print(f"{label:<40} {cpu_val:>20} {gpu_val:>20}")

        has_cpu_rss = ('cpu_rss_peak_bytes' in cpu_mem or 'cpu_rss_peak_bytes' in gpu_mem)
        if has_cpu_rss:
            print()
            print("CPU Memory (RSS via /proc):")
            print(f"{'Metric':<40} {'CPU Mode':>20} {'GPU Mode':>20}")
            print("-" * 82)
            for label, key in [('RSS Baseline', 'cpu_rss_baseline_bytes'),
                               ('RSS Peak', 'cpu_rss_peak_bytes'),
                               ('RSS Delta (peak - baseline)', 'cpu_rss_delta_bytes')]:
                cpu_val = _fmt_bytes(cpu_mem[key]) if key in cpu_mem else '-'
                gpu_val = _fmt_bytes(gpu_mem[key]) if key in gpu_mem else '-'
                print(f"{label:<40} {cpu_val:>20} {gpu_val:>20}")
        print()

    # ── Section 2: CPU-Only Functions ───────────────────────────────────
    print("=" * 100)
    print("SECTION 2: CPU-ONLY MODE - ALL TRACED FUNCTIONS")
    print("=" * 100)
    print()

    stages_cpu = {}
    for name, info in cpu_funcs.items():
        stages_cpu.setdefault(info['stage'], []).append((name, info))

    for stage in PIPELINE_STAGES:
        if stage not in stages_cpu:
            continue
        funcs = stages_cpu[stage]
        funcs.sort(key=lambda x: -x[1]['time_us'])
        total_time = sum(f[1]['time_us'] for f in funcs)
        print(f"--- {stage.upper()} ({format_duration(total_time)} total, {len(funcs)} functions) ---")
        print(f"{'Function':<40} {'Time':>15} {'Calls':>10} {'File':<30}")
        print("-" * 100)
        for name, info in funcs:
            print(f"{name:<40} {format_duration(info['time_us']):>15} {info['count']:>10} {info['file']:<30}")
        print()

    # ── Section 3: GPU Mode Functions ───────────────────────────────────
    print("=" * 100)
    print("SECTION 3: GPU MODE - ALL TRACED FUNCTIONS")
    print("=" * 100)
    print()

    stages_gpu = {}
    for name, info in gpu_funcs.items():
        stages_gpu.setdefault(info['stage'], []).append((name, info))

    for stage in PIPELINE_STAGES:
        if stage not in stages_gpu:
            continue
        funcs = stages_gpu[stage]
        funcs.sort(key=lambda x: -x[1]['time_us'])
        total_time = sum(f[1]['time_us'] for f in funcs)
        print(f"--- {stage.upper()} ({format_duration(total_time)} total, {len(funcs)} functions) ---")
        print(f"{'Function':<40} {'Time':>15} {'Calls':>10} {'File':<30}")
        print("-" * 100)
        for name, info in funcs:
            print(f"{name:<40} {format_duration(info['time_us']):>15} {info['count']:>10} {info['file']:<30}")
        print()

    # ── Section 4: GPU Kernel Bottleneck Analysis ───────────────────────
    print("=" * 100)
    print("SECTION 4: GPU KERNEL BOTTLENECK ANALYSIS")
    print("=" * 100)
    print()

    if gpu_kernels:
        all_kernel_total = sum(info['time_us'] for info in gpu_kernels.values())

        kernels_by_stage = {}
        for name, info in gpu_kernels.items():
            kernels_by_stage.setdefault(info['stage'], []).append((name, info))

        for stage in PIPELINE_STAGES:
            if stage not in kernels_by_stage:
                continue
            kernels = kernels_by_stage[stage]
            kernels.sort(key=lambda x: -x[1]['time_us'])
            stage_time = sum(k[1]['time_us'] for k in kernels)
            print(f"--- {stage.upper()} ({format_duration(stage_time)} total, {len(kernels)} kernels) ---")
            print(f"{'Kernel':<50} {'Total':>12} {'Calls':>8} {'Avg/Call':>12} {'% GPU':>7}")
            print("-" * 93)
            for name, info in kernels:
                display_name = name[:47] + "..." if len(name) > 50 else name
                count = info['count']
                avg_us = info['time_us'] / count if count else 0
                pct = (info['time_us'] / all_kernel_total * 100) if all_kernel_total else 0
                print(f"{display_name:<50} {format_duration(info['time_us']):>12} {count:>8,} {format_duration(avg_us):>12} {pct:>6.1f}%")
            print()

        print("--- TOP BOTTLENECKS BY AVG TIME PER CALL ---")
        all_kerns = sorted(gpu_kernels.items(),
                           key=lambda x: (x[1]['time_us'] / x[1]['count'] if x[1]['count'] else 0),
                           reverse=True)
        print(f"{'Kernel':<50} {'Avg/Call':>12} {'Calls':>8} {'Total':>12} {'% GPU':>7}")
        print("-" * 93)
        for name, info in all_kerns:
            display_name = name[:47] + "..." if len(name) > 50 else name
            count = info['count']
            avg_us = info['time_us'] / count if count else 0
            pct = (info['time_us'] / all_kernel_total * 100) if all_kernel_total else 0
            print(f"{display_name:<50} {format_duration(avg_us):>12} {count:>8,} {format_duration(info['time_us']):>12} {pct:>6.1f}%")
        print()

        # Hardware counter & resource summary
        if gpu_counters:
            print("--- KERNEL RESOURCES & HARDWARE COUNTERS ---")
            print(f"{'Kernel':<35} {'VGPR':>5} {'SGPR':>5} {'LDS':>6} {'Scratch':>7} "
                  f"{'VALU%':>6} {'VMEM%':>6} {'LDS%':>5} {'Occ%':>5} {'Bound':>8}")
            print("-" * 98)
            for name in sorted(gpu_counters,
                               key=lambda k: gpu_kernels.get(k, {}).get('time_us', 0),
                               reverse=True):
                kc = gpu_counters[name]
                res = kc.get('resources', {})
                der = kc.get('derived', {})
                display_name = name[:32] + "..." if len(name) > 35 else name
                vgpr = str(res.get('Arch_VGPR', '-'))
                sgpr = str(res.get('SGPR', '-'))
                lds = str(res.get('LDS_Per_Workgroup', '-'))
                scratch = str(res.get('Scratch_Per_Workitem', '-'))
                valu = f"{der['valu_pct']:.0f}" if 'valu_pct' in der else '-'
                vmem = f"{der['vmem_pct']:.0f}" if 'vmem_pct' in der else '-'
                lds_pct = f"{der['lds_pct']:.0f}" if 'lds_pct' in der else '-'
                occ = f"{der['occupancy_pct']:.0f}" if 'occupancy_pct' in der else '-'
                cls_str = der.get('classification', '-')
                print(f"{display_name:<35} {vgpr:>5} {sgpr:>5} {lds:>6} {scratch:>7} "
                      f"{valu:>6} {vmem:>6} {lds_pct:>5} {occ:>5} {cls_str:>8}")

            low_occ = [(k, kc['derived']['occupancy_pct'], kc['derived'].get('occupancy_limiter', ''))
                       for k, kc in gpu_counters.items()
                       if kc.get('derived', {}).get('occupancy_pct', 100) < 50]
            if low_occ:
                print()
                print("  Warning - Low Occupancy (< 50%):")
                for kname, occ_pct, limiter in sorted(low_occ, key=lambda x: x[1]):
                    short = kname[:60] + '...' if len(kname) > 63 else kname
                    print(f"    {short}: {occ_pct:.0f}% (limited by {limiter})")

            conflicts = [(k, kc['derived']['lds_conflict_rate'])
                         for k, kc in gpu_counters.items()
                         if kc.get('derived', {}).get('lds_conflict_rate', 0) > 5]
            if conflicts:
                print()
                print("  Warning - LDS Bank Conflicts:")
                for kname, rate in sorted(conflicts, key=lambda x: -x[1]):
                    short = kname[:60] + '...' if len(kname) > 63 else kname
                    print(f"    {short}: {rate:.1f}% conflict rate")
            print()

        # Host <-> Device transfer breakdown
        transfers = extract_transfers(gpu_api_calls)
        if transfers:
            print("--- HOST <-> DEVICE TRANSFERS ---")
            total_xfer = sum(v['time_us'] for v in transfers.values())
            total_bytes = sum(v['bytes_total'] for v in transfers.values())
            has_bytes = total_bytes > 0
            if has_bytes:
                print(f"{'Operation':<32} {'Total Time':>12} {'Calls':>8} {'Bytes':>12} {'BW (GB/s)':>10} {'% Xfer':>7}")
                print("-" * 85)
            else:
                print(f"{'Operation':<40} {'Total Time':>12} {'Calls':>8} {'Avg/Call':>12} {'% Xfer':>7}")
                print("-" * 83)
            for name in sorted(transfers, key=lambda n: transfers[n]['time_us'], reverse=True):
                info = transfers[name]
                avg = info['time_us'] / info['count'] if info['count'] else 0
                pct = info['time_us'] / total_xfer * 100 if total_xfer else 0
                if has_bytes:
                    bw = info['bytes_total'] / (info['time_us'] / 1e6) / 1e9 if info['time_us'] > 0 else 0
                    print(f"{name:<32} {format_duration(info['time_us']):>12} {info['count']:>8,} "
                          f"{_fmt_bytes(info['bytes_total']):>12} {bw:>9.2f} {pct:>6.1f}%")
                else:
                    print(f"{name:<40} {format_duration(info['time_us']):>12} {info['count']:>8,} "
                          f"{format_duration(avg):>12} {pct:>6.1f}%")
            if has_bytes:
                total_bw = total_bytes / (total_xfer / 1e6) / 1e9 if total_xfer > 0 else 0
                print(f"{'TOTAL':<32} {format_duration(total_xfer):>12} {'':>8} "
                      f"{_fmt_bytes(total_bytes):>12} {total_bw:>9.2f}")
            else:
                print(f"{'TOTAL':<40} {format_duration(total_xfer):>12}")
            if gpu_kernel_total > 0:
                print(f"  Transfer overhead vs kernel time: {total_xfer / gpu_kernel_total * 100:.1f}%")
            print()

        # HIP API overhead summary
        hip_calls = {n: v for n, v in gpu_api_calls.items()
                     if n.startswith('hip') and n not in transfers}
        if hip_calls:
            total_hip = sum(v['time_us'] for v in hip_calls.values())
            print("--- HIP API OVERHEAD (top 15 by time) ---")
            print(f"{'API Call':<40} {'Total Time':>12} {'Calls':>8} {'Avg/Call':>12}")
            print("-" * 76)
            top_hip = sorted(hip_calls.items(), key=lambda x: x[1]['time_us'], reverse=True)[:15]
            for name, info in top_hip:
                avg = info['time_us'] / info['count'] if info['count'] else 0
                print(f"{name:<40} {format_duration(info['time_us']):>12} {info['count']:>8,} "
                      f"{format_duration(avg):>12}")
            print(f"{'TOTAL HIP API':<40} {format_duration(total_hip):>12}")
            if gpu_kernel_total > 0:
                print(f"  HIP API overhead vs kernel time: {total_hip / gpu_kernel_total * 100:.1f}%")
            print()

        # Synchronization overlap analysis
        sync_analysis = analyze_sync_overlap(gpu_api_calls, gpu_kernels, gpu_kernel_total)
        if sync_analysis:
            print("--- SYNCHRONIZATION & OVERLAP ANALYSIS ---")
            sa = sync_analysis
            print(f"  hipDeviceSynchronize: {format_duration(sa['sync_time_us'])} ({sa['sync_count']:,} calls)")
            print(f"  hipLaunchKernel:      {sa['user_kernel_count']:,} user kernel launches")
            print(f"  GPU kernel dispatches: {format_duration(gpu_kernel_total)} ({sa['kernel_count']:,} total dispatches)")
            if sa['dominant_kernel']:
                dk_name, dk_time, dk_count = sa['dominant_kernel']
                print(f"  Dominant kernel:      {dk_name} ({format_duration(dk_time)}, {dk_count:,} calls)")
            if sa['is_sync_waiting']:
                reasons = []
                if sa['sync_matches_launches']:
                    reasons.append(f"sync count ({sa['sync_count']:,}) ≈ launch count ({sa['user_kernel_count']:,})")
                if sa['sync_approx_kernel_time']:
                    reasons.append(f"sync time ({format_duration(sa['sync_time_us'])}) ≈ kernel time ({format_duration(gpu_kernel_total)})")
                print(f"  Pattern: SYNCHRONOUS DISPATCH detected ({'; '.join(reasons)})")
                print(f"  → Each kernel launch is followed by hipDeviceSynchronize (waiting for completion)")
                print(f"  → {format_duration(sa['overlap_us'])} of sync time OVERLAPS with kernel execution (not extra overhead)")
                print(f"  → True sync overhead (non-overlapping): {format_duration(sa['sync_overhead_us'])}")
            else:
                print(f"  Pattern: sync calls do not clearly match kernel dispatches")
            print()
            print("  HIP API Time Breakdown:")
            print(f"    Sync wait (overlapped with kernels): {format_duration(sa['overlap_us'])}")
            print(f"    Memory alloc/free (hipMalloc+hipFree+hipHostMalloc+hipHostFree): "
                  f"{format_duration(sa['alloc_time_us'])} ({sa['alloc_count']:,} calls)")
            print(f"    Memory copy (hipMemcpy*):            {format_duration(sa['memcpy_time_us'])} ({sa['memcpy_count']:,} calls)")
            print(f"    Kernel launch overhead:              {format_duration(sa['launch_time_us'])}")
            print(f"    Memory set (hipMemset*):             {format_duration(sa['memset_time_us'])}")
            real_overhead = sa['real_api_overhead_us']
            print(f"    ─────────────────────────────────────")
            print(f"    Real HIP API overhead:               {format_duration(real_overhead)}")
            if gpu_kernel_total > 0:
                print(f"    Real overhead vs kernel time:         {real_overhead / gpu_kernel_total * 100:.1f}%")
            print()
    else:
        print("No GPU kernels found.")
        print()

    # ── Section 5: Function Comparison ──────────────────────────────────
    print("=" * 100)
    print("SECTION 5: FUNCTION COMPARISON (CPU vs GPU)")
    print("=" * 100)
    print()

    all_func_names = set(cpu_funcs.keys()) | set(gpu_funcs.keys())
    replaced = []
    increased = []
    new_gpu = []

    for name in all_func_names:
        cpu_info = cpu_funcs.get(name)
        gpu_info = gpu_funcs.get(name)
        if cpu_info and not gpu_info:
            replaced.append((name, cpu_info, None))
        elif gpu_info and not cpu_info:
            new_gpu.append((name, None, gpu_info))
        else:
            cpu_time = cpu_info['time_us']
            gpu_time = gpu_info['time_us']
            if cpu_time > 0 and gpu_time / cpu_time > 10:
                increased.append((name, cpu_info, gpu_info))

    print("### 5.1 CPU FUNCTIONS REPLACED BY GPU")
    print()
    if replaced:
        replaced.sort(key=lambda x: -x[1]['time_us'])
        print(f"{'Function':<40} {'CPU Time':>15} {'Stage':<15} {'File':<25}")
        print("-" * 100)
        total_replaced = 0
        for name, cpu_info, _ in replaced:
            print(f"{name:<40} {format_duration(cpu_info['time_us']):>15} {cpu_info['stage']:<15} {cpu_info['file']:<25}")
            total_replaced += cpu_info['time_us']
        print("-" * 100)
        print(f"{'TOTAL REPLACED':<40} {format_duration(total_replaced):>15}")
    else:
        print("(No functions completely replaced)")
    print()

    print("### 5.2 FUNCTIONS WITH GPU OVERHEAD")
    print()
    if increased:
        increased.sort(key=lambda x: -(x[2]['time_us'] - x[1]['time_us']))
        print(f"{'Function':<35} {'CPU Time':>12} {'GPU Time':>12} {'Overhead':>12} {'Stage':<12}")
        print("-" * 90)
        for name, cpu_info, gpu_info in increased[:15]:
            overhead = gpu_info['time_us'] - cpu_info['time_us']
            print(f"{name:<35} {format_duration(cpu_info['time_us']):>12} {format_duration(gpu_info['time_us']):>12} {format_duration(overhead):>12} {cpu_info['stage']:<12}")
    else:
        print("(No functions with significant overhead)")
    print()

    print("### 5.3 NEW FUNCTIONS IN GPU MODE")
    print()
    if new_gpu:
        new_gpu.sort(key=lambda x: -x[2]['time_us'])
        print(f"{'Function':<40} {'GPU Time':>15} {'Stage':<15} {'File':<25}")
        print("-" * 100)
        for name, _, gpu_info in new_gpu:
            print(f"{name:<40} {format_duration(gpu_info['time_us']):>15} {gpu_info['stage']:<15} {gpu_info['file']:<25}")
    else:
        print("(No new GPU-only functions)")
    print()

    # ── Section 6: Summary & Bottleneck Identification ──────────────────
    print("=" * 100)
    print("SECTION 6: SUMMARY & BOTTLENECK IDENTIFICATION")
    print("=" * 100)
    print()

    total_replaced_time = sum(cpu_funcs.get(name, {}).get('time_us', 0) for name, _, _ in replaced)
    total_kernel_time = sum(k['time_us'] for k in gpu_kernels.values())

    print(f"  • CPU functions replaced by GPU: {len(replaced)}")
    print(f"  • Total CPU compute time replaced: {format_duration(total_replaced_time)}")
    print(f"  • Total GPU kernel time: {format_duration(total_kernel_time)}")
    print()

    if gpu_total > 0 and cpu_total > gpu_total:
        print(f"  ✓ GPU mode is {cpu_total/gpu_total:.2f}x FASTER overall")
    elif cpu_total > 0 and gpu_total > cpu_total:
        print(f"  ✗ GPU mode is {gpu_total/cpu_total:.2f}x SLOWER overall")
    elif cpu_total > 0 and gpu_total > 0:
        print("  = GPU mode is the same speed as CPU mode")
    else:
        print("  ? Insufficient timing data for comparison")
    print()

    if stage_rows and gpu_total > 0:
        print("  BOTTLENECK ANALYSIS (GPU mode):")
        print()
        ranked = sorted(stage_rows, key=lambda r: r[3], reverse=True)
        bottleneck = ranked[0]
        bn_stage, _, _, bn_time, bn_pct, bn_kernel, bn_speedup, _ = bottleneck
        print(f"    Bottleneck stage: {bn_stage.upper()}")
        print(f"      Time: {format_duration(bn_time)} ({bn_pct:.1f}% of total GPU-mode time)")
        if bn_kernel > 0:
            print(f"      GPU kernel time: {format_duration(bn_kernel)}")
        if bn_speedup > 0:
            if bn_speedup >= 1:
                print(f"      vs CPU: {bn_speedup:.2f}x faster")
            else:
                print(f"      vs CPU: {1/bn_speedup:.2f}x slower")
        print()

        regressions = [(s, ct, gt, sp) for s, ct, _, gt, _, _, sp, _ in stage_rows
                       if sp > 0 and sp < 1.0]
        if regressions:
            print("    Stages with REGRESSION (GPU slower than CPU):")
            for stg, ct, gt, sp in sorted(regressions, key=lambda x: x[3]):
                overhead = gt - ct
                print(f"      {stg.upper()}: {1/sp:.2f}x slower (+{format_duration(overhead)})")
            print()

        bn_cpu_time = bottleneck[1]
        if bn_cpu_time > 0 and bn_time > bn_cpu_time:
            potential_saving = bn_time - bn_cpu_time
            new_total = gpu_total - potential_saving
            print(f"    Potential: eliminating {bn_stage.upper()} overhead saves {format_duration(potential_saving)}")
            if new_total > 0 and cpu_total > 0:
                print(f"              projected total: {format_duration(new_total)} ({cpu_total/new_total:.2f}x vs CPU)")
            print()

        # CU underutilization analysis
        kernel_occ = gpu_data.get('kernel_occupancy', [])
        underutilized = [k for k in kernel_occ if k['cu_coverage_pct'] < 50]
        if underutilized:
            underutilized.sort(key=lambda k: -k['total_time_us'])
            print("    CU UNDERUTILIZATION (primary optimization target):")
            for k in underutilized:
                short_name = k['name'].split('(')[0].strip()
                max_batch = min(k['num_cus'] // max(k['waves_per_dispatch'], 1),
                                k['dispatch_count'])
                kernel_s = k['total_time_us'] / 1e6
                print(f"      {short_name}: {k['cu_coverage_pct']:.1f}% CU coverage "
                      f"({k['waves_per_dispatch']} wave / {k['num_cus']} CUs), "
                      f"{k['dispatch_count']:,} dispatches, {kernel_s:.1f}s total")
                if max_batch > 1:
                    batched_s = kernel_s / max_batch
                    print(f"      → Batching to fill all CUs: ~{batched_s:.1f}s kernel time "
                          f"(projected {cpu_total / (gpu_total - kernel_s + batched_s):.1f}x vs CPU)")
            print()

        # Memory footprint
        cpu_mem = cpu_data.get('summary', {}).get('gpu_memory', {})
        gpu_mem_data = gpu_data.get('summary', {}).get('gpu_memory', {})
        cpu_rss = gpu_mem_data.get('cpu_rss_peak_bytes', 0)
        cpu_rss_baseline = cpu_mem.get('cpu_rss_peak_bytes', 0)
        if cpu_rss > 0 and cpu_rss_baseline > 0 and cpu_rss > 2 * cpu_rss_baseline:
            print(f"    MEMORY: GPU mode RSS {_fmt_bytes(cpu_rss)} vs CPU-only "
                  f"{_fmt_bytes(cpu_rss_baseline)} ({cpu_rss / cpu_rss_baseline:.1f}x increase)")
            print()

        # hipHostMalloc high per-call cost
        for api_name, api_info in gpu_api_calls.items():
            if api_name in ('hipHostMalloc', 'hipHostFree'):
                if api_info['time_us'] > 1e6 and api_info['count'] > 0:  # > 1s total
                    avg_ms = api_info['time_us'] / api_info['count'] / 1000
                    print(f"    NOTE: {api_name} called {api_info['count']:,} times "
                          f"({format_duration(api_info['time_us'])}, {avg_ms:.0f}ms/call) "
                          f"— pre-allocate pinned buffers or use a pinned memory pool")

    print("=" * 100)


# ═══════════════════════════════════════════════════════════════════════════
# Graph generation (matplotlib)
# ═══════════════════════════════════════════════════════════════════════════

def _collect_stage_times(cpu_data: dict, gpu_data: dict) -> Tuple[dict, dict, dict, float, float, float]:
    """Collect per-stage trace/kernel times and totals for graphs."""
    cpu_trace = {s: cpu_data['stages'].get(s, {}).get('trace_time_us', 0) / 1e6 for s in GRAPH_STAGES}
    gpu_trace = {s: gpu_data['stages'].get(s, {}).get('trace_time_us', 0) / 1e6 for s in GRAPH_STAGES}
    gpu_kernel = {s: gpu_data['stages'].get(s, {}).get('gpu_time_us', 0) / 1e6 for s in GRAPH_STAGES}
    cpu_total = cpu_data['summary']['total_trace_time_us'] / 1e6
    gpu_total = gpu_data['summary']['total_trace_time_us'] / 1e6
    gpu_kernel_total = gpu_data['summary']['total_gpu_time_us'] / 1e6
    return cpu_trace, gpu_trace, gpu_kernel, cpu_total, gpu_total, gpu_kernel_total


def generate_graphs(cpu_data: dict, gpu_data: dict, out_dir: str):
    """Generate all matplotlib graphs into out_dir."""
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    import numpy as np

    cpu_trace, gpu_trace, gpu_kernel, cpu_total, gpu_total, gpu_kernel_total = \
        _collect_stage_times(cpu_data, gpu_data)

    # ── 1. Per-stage timing bar chart ───────────────────────────────────
    fig, ax = plt.subplots(figsize=(10, 5))
    x = np.arange(len(GRAPH_STAGES))
    w = 0.35
    bars_cpu = ax.bar(x - w/2, [cpu_trace[s] for s in GRAPH_STAGES], w,
                      label='CPU-only', color='#2196F3', edgecolor='white')
    bars_gpu = ax.bar(x + w/2, [gpu_trace[s] for s in GRAPH_STAGES], w,
                      label='GPU mode (wall)', color='#FF9800', edgecolor='white')
    ax.bar(x + w/2, [gpu_kernel[s] for s in GRAPH_STAGES], w,
           label='GPU kernel', color='#E65100', edgecolor='white', hatch='///', alpha=0.7)
    ax.set_ylabel('Time (seconds)')
    ax.set_title('Per-Stage Timing: CPU vs GPU')
    ax.set_xticks(x)
    ax.set_xticklabels([s.upper() for s in GRAPH_STAGES])
    ax.legend()
    ax.grid(axis='y', alpha=0.3)
    for bar in bars_cpu:
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 2,
                f'{bar.get_height():.1f}s', ha='center', va='bottom', fontsize=8)
    for bar in bars_gpu:
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 2,
                f'{bar.get_height():.1f}s', ha='center', va='bottom', fontsize=8)
    plt.tight_layout()
    plt.savefig(os.path.join(out_dir, 'stage_timing.png'), dpi=150)
    plt.close()

    # ── 2. Pie chart (CPU vs GPU) ──────────────────────────────────────
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))
    cpu_vals = [cpu_trace[s] for s in GRAPH_STAGES]
    gpu_vals = [gpu_trace[s] for s in GRAPH_STAGES]
    colors = [STAGE_COLORS[s] for s in GRAPH_STAGES]
    ax1.pie(cpu_vals, labels=[s.upper() for s in GRAPH_STAGES], autopct='%1.1f%%',
            colors=colors, startangle=90)
    ax1.set_title(f'CPU-only ({cpu_total:.0f}s total)')
    ax2.pie(gpu_vals, labels=[s.upper() for s in GRAPH_STAGES], autopct='%1.1f%%',
            colors=colors, startangle=90)
    ax2.set_title(f'GPU mode ({gpu_total:.0f}s total)')
    plt.tight_layout()
    plt.savefig(os.path.join(out_dir, 'stage_pie.png'), dpi=150)
    plt.close()

    # ── 3. GPU kernel bottleneck ───────────────────────────────────────
    all_kernels = []
    for stage in GRAPH_STAGES + ['gpu_other']:
        for k in gpu_data['stages'].get(stage, {}).get('gpu_kernels', []):
            all_kernels.append((k['name'].split('(')[0].strip(),
                                k['duration_us'] / 1e6, k['count'], stage))
    all_kernels.sort(key=lambda x: -x[1])

    if all_kernels:
        top = all_kernels[:8]
        fig, ax = plt.subplots(figsize=(10, 5))
        names = [k[0][:40] for k in top]
        times = [k[1] for k in top]
        counts = [k[2] for k in top]
        stage_cols = [STAGE_COLORS.get(k[3], '#9E9E9E') for k in top]
        bars = ax.barh(range(len(top)), times, color=stage_cols, edgecolor='white')
        ax.set_yticks(range(len(top)))
        ax.set_yticklabels(names, fontsize=8)
        ax.set_xlabel('Total GPU Time (seconds)')
        ax.set_title('GPU Kernel Bottleneck Analysis')
        ax.invert_yaxis()
        for i, (bar, cnt) in enumerate(zip(bars, counts)):
            ax.text(bar.get_width() + 0.5, bar.get_y() + bar.get_height()/2,
                    f'{bar.get_width():.2f}s ({cnt} calls)', va='center', fontsize=8)
        ax.grid(axis='x', alpha=0.3)
        plt.tight_layout()
        plt.savefig(os.path.join(out_dir, 'kernel_bottleneck.png'), dpi=150)
        plt.close()

    # ── 4. Copy memory timeline from GPU run ───────────────────────────
    gpu_dir = os.path.dirname(os.path.abspath(sys.argv[2])) if len(sys.argv) > 2 else ''
    mem_src = os.path.join(gpu_dir, 'memory_timeline.png') if gpu_dir else ''
    if mem_src and os.path.exists(mem_src):
        shutil.copy2(mem_src, os.path.join(out_dir, 'memory_timeline.png'))

    # ── 5. Speedup bar chart ──────────────────────────────────────────
    fig, ax = plt.subplots(figsize=(8, 4))
    speedups = []
    for s in GRAPH_STAGES:
        c = cpu_trace[s]
        g = gpu_trace[s]
        speedups.append(c / g if g > 0 else 0)
    colors_speed = ['#4CAF50' if sp > 1 else '#F44336' for sp in speedups]
    bars = ax.bar(range(len(GRAPH_STAGES)), speedups, color=colors_speed, edgecolor='white')
    ax.axhline(y=1.0, color='black', linestyle='--', alpha=0.5, label='Break-even')
    ax.set_xticks(range(len(GRAPH_STAGES)))
    ax.set_xticklabels([s.upper() for s in GRAPH_STAGES])
    ax.set_ylabel('Speedup (CPU/GPU)')
    ax.set_title('Per-Stage Speedup (>1 = GPU faster)')
    for bar, sp in zip(bars, speedups):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.02,
                f'{sp:.2f}x', ha='center', va='bottom', fontsize=10, fontweight='bold')
    ax.legend()
    ax.grid(axis='y', alpha=0.3)
    plt.tight_layout()
    plt.savefig(os.path.join(out_dir, 'speedup.png'), dpi=150)
    plt.close()

    # ── 6. HIP API overhead ──────────────────────────────────────────
    hip_calls = []
    for stage in gpu_data['stages']:
        for h in gpu_data['stages'].get(stage, {}).get('gpu_api_calls', []):
            # Exclude hardware DMA entries (memcpy_memcpy etc.) — they're not HIP API calls
            if not h['name'].startswith('memcpy_'):
                hip_calls.append((h['name'], h['duration_us'] / 1e6, h['count']))
    hip_calls.sort(key=lambda x: -x[1])
    top_hip = hip_calls[:10]
    if top_hip:
        fig, ax = plt.subplots(figsize=(10, 5))
        names = [h[0] for h in top_hip]
        times = [h[1] for h in top_hip]
        bars = ax.barh(range(len(top_hip)), times, color='#7B1FA2', edgecolor='white', alpha=0.8)
        ax.set_yticks(range(len(top_hip)))
        ax.set_yticklabels(names, fontsize=8)
        ax.set_xlabel('Total Time (seconds)')
        ax.set_title('HIP API Overhead (Top 10)')
        ax.invert_yaxis()
        for bar in bars:
            ax.text(bar.get_width() + 0.1, bar.get_y() + bar.get_height()/2,
                    f'{bar.get_width():.2f}s', va='center', fontsize=8)
        ax.grid(axis='x', alpha=0.3)
        plt.tight_layout()
        plt.savefig(os.path.join(out_dir, 'hip_api_overhead.png'), dpi=150)
        plt.close()

    # ── 7. VTune function heatmap ─────────────────────────────────────
    fig, axes = plt.subplots(1, len(GRAPH_STAGES), figsize=(16, 6), sharey=False)
    for i, stage in enumerate(GRAPH_STAGES):
        ax = axes[i]
        cpu_fns = cpu_data['stages'].get(stage, {}).get('vtune_minimap2_functions', [])[:8]
        if cpu_fns:
            names = [f['name'][:25] for f in cpu_fns]
            times = [f['cpu_time_ms'] / 1000 for f in cpu_fns]
            ax.barh(range(len(cpu_fns)), times, color=STAGE_COLORS[stage], alpha=0.8)
            ax.set_yticks(range(len(cpu_fns)))
            ax.set_yticklabels(names, fontsize=7)
            ax.invert_yaxis()
        ax.set_xlabel('CPU Time (s)')
        ax.set_title(f'{stage.upper()} (VTune)')
    plt.suptitle('VTune CPU Hotspot Functions by Stage (CPU-only mode)', fontsize=12)
    plt.tight_layout()
    plt.savefig(os.path.join(out_dir, 'vtune_hotspots.png'), dpi=150)
    plt.close()

    print(f"Graphs saved to {out_dir}/")


# ═══════════════════════════════════════════════════════════════════════════
# Markdown report generation
# ═══════════════════════════════════════════════════════════════════════════

def generate_markdown_report(cpu_data: dict, gpu_data: dict, out_dir: str):
    """Generate PROFILING_REPORT.md with embedded graph references."""
    cpu_trace, gpu_trace, gpu_kernel, cpu_total, gpu_total, gpu_kernel_total = \
        _collect_stage_times(cpu_data, gpu_data)

    overall_speedup = cpu_total / gpu_total if gpu_total > 0 else 0
    cpu_mem = cpu_data['summary'].get('gpu_memory', {})
    gpu_mem = gpu_data['summary'].get('gpu_memory', {})

    md: List[str] = []
    md.append("# Minimap2 CPU vs GPU Profiling Report")
    md.append(f"\n**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  ")
    md.append(f"**Binary:** profile preset (v{cpu_data['summary'].get('version', 'N/A')})")

    # ── 1. Overall Summary ──────────────────────────────────────────────
    md.append("\n## 1. Overall Summary\n")
    if overall_speedup >= 1:
        md.append(f"**Overall: GPU mode is {overall_speedup:.2f}x FASTER**\n")
    else:
        md.append(f"**Overall: GPU mode is {1/overall_speedup:.2f}x SLOWER**\n")

    md.append("| Metric | CPU-only | GPU mode | Delta |")
    md.append("|--------|----------|----------|-------|")
    md.append(f"| Total wall time | {cpu_total:.1f}s | {gpu_total:.1f}s | {gpu_total - cpu_total:+.1f}s |")
    md.append(f"| GPU kernel time | — | {gpu_kernel_total:.1f}s | — |")
    if gpu_mem:
        md.append(f"| VRAM peak | {_fmt_bytes(cpu_mem.get('vram_peak_bytes', 0))} | {_fmt_bytes(gpu_mem.get('vram_peak_bytes', 0))} | — |")
        md.append(f"| VRAM delta | {_fmt_bytes(cpu_mem.get('vram_delta_bytes', 0))} | {_fmt_bytes(gpu_mem.get('vram_delta_bytes', 0))} | — |")
        md.append(f"| CPU RSS peak | {_fmt_bytes(cpu_mem.get('cpu_rss_peak_bytes', 0))} | {_fmt_bytes(gpu_mem.get('cpu_rss_peak_bytes', 0))} | — |")
    md.append("\n![Stage Timing](stage_timing.png)\n")

    # ── 2. Per-Stage Breakdown ──────────────────────────────────────────
    md.append("## 2. Per-Stage Breakdown\n")
    md.append("| Stage | CPU Time | %CPU | GPU Time | %GPU | GPU Kernel | Speedup |")
    md.append("|-------|----------|------|----------|------|------------|---------|")
    for s in GRAPH_STAGES:
        ct, gt, gk = cpu_trace[s], gpu_trace[s], gpu_kernel[s]
        cp = ct / cpu_total * 100 if cpu_total else 0
        gp = gt / gpu_total * 100 if gpu_total else 0
        sp = ct / gt if gt > 0 else 0
        gk_str = f"{gk:.2f}s" if gk > 0 else "—"
        sp_str = f"**{sp:.2f}x**" if sp > 1 else f"{sp:.2f}x"
        md.append(f"| {s.upper()} | {ct:.1f}s | {cp:.1f}% | {gt:.1f}s | {gp:.1f}% | {gk_str} | {sp_str} |")
    md.append("\n![Stage Pie](stage_pie.png)\n")
    md.append("\n![Speedup](speedup.png)\n")

    # ── 3. CPU Traced Functions ─────────────────────────────────────────
    md.append("## 3. CPU Traced Functions\n")
    for s in GRAPH_STAGES:
        fns = cpu_data['stages'].get(s, {}).get('trace_functions', [])
        if not fns:
            continue
        md.append(f"### {s.upper()} ({cpu_trace[s]:.1f}s, {len(fns)} functions)\n")
        md.append("| Function | Time | Calls | File |")
        md.append("|----------|------|-------|------|")
        for fn in fns[:10]:
            md.append(f"| `{fn['name']}` | {_fmt_s(fn['duration_us'])} | {fn['count']:,} | {fn.get('file', '')} |")
        md.append("")

    # ── 4. GPU Traced Functions ─────────────────────────────────────────
    md.append("## 4. GPU Traced Functions\n")
    for s in GRAPH_STAGES:
        fns = gpu_data['stages'].get(s, {}).get('trace_functions', [])
        if not fns:
            continue
        md.append(f"### {s.upper()} ({gpu_trace[s]:.1f}s, {len(fns)} functions)\n")
        md.append("| Function | Time | Calls | File |")
        md.append("|----------|------|-------|------|")
        for fn in fns[:10]:
            md.append(f"| `{fn['name']}` | {_fmt_s(fn['duration_us'])} | {fn['count']:,} | {fn.get('file', '')} |")
        md.append("")

    # ── 5. VTune Hotspots ───────────────────────────────────────────────
    md.append("## 5. VTune CPU Hotspot Functions\n")
    md.append("![VTune Hotspots](vtune_hotspots.png)\n")
    for mode_label, data in [("CPU-only", cpu_data), ("GPU mode", gpu_data)]:
        for s in GRAPH_STAGES:
            fns = data['stages'].get(s, {}).get('vtune_minimap2_functions', [])
            if not fns:
                continue
            total_ms = data['stages'][s].get('vtune_minimap2_total_ms', 0)
            md.append(f"### {mode_label}: {s.upper()} ({total_ms/1000:.1f}s VTune time, {len(fns)} functions)\n")
            md.append("| Function | CPU Time |")
            md.append("|----------|----------|")
            for fn in fns[:10]:
                md.append(f"| `{fn['name']}` | {fn['cpu_time_ms']/1000:.2f}s |")
            md.append("")

    # ── 6. GPU Kernel Bottleneck Analysis ───────────────────────────────
    md.append("## 6. GPU Kernel Bottleneck Analysis\n")
    md.append("![Kernel Bottleneck](kernel_bottleneck.png)\n")
    for stage in GRAPH_STAGES + ['gpu_other']:
        kernels = gpu_data['stages'].get(stage, {}).get('gpu_kernels', [])
        if not kernels:
            continue
        stage_gpu = gpu_data['stages'][stage].get('gpu_time_us', 0) / 1e6
        md.append(f"### {stage.upper()} ({stage_gpu:.2f}s GPU kernel time)\n")
        md.append("| Kernel | Total | Calls | Avg/Call | % GPU |")
        md.append("|--------|-------|-------|----------|-------|")
        total_gpu_us = gpu_data['summary']['total_gpu_time_us']
        for k in kernels:
            name = k['name'].split('(')[0].strip()[:50]
            dur = k['duration_us'] / 1e6
            cnt = k['count']
            avg = k['duration_us'] / cnt if cnt else 0
            pct = k['duration_us'] / total_gpu_us * 100 if total_gpu_us else 0
            md.append(f"| `{name}` | {dur:.2f}s | {cnt:,} | {_fmt_s(avg)} | {pct:.1f}% |")
        md.append("")

    # ── 7. GPU Kernel Occupancy & CU Utilization ──────────────────────
    kernel_occ = gpu_data.get('kernel_occupancy', [])
    if kernel_occ:
        md.append("## 7. GPU Kernel Occupancy & CU Utilization\n")
        md.append("Theoretical occupancy and Compute-Unit (CU) coverage per dispatch, "
                  "derived from kernel register/LDS usage and grid dimensions in the "
                  "rocprofv3 trace.\n")
        md.append("| Kernel | Dispatches | Total | Avg | WG | Grid | VGPRs | LDS | Occupancy | CU Coverage |")
        md.append("|--------|-----------|-------|-----|-----|------|-------|-----|-----------|-------------|")
        for k in kernel_occ:
            short_name = k['name'].split('(')[0].strip()
            # Truncate template args for readability
            if '<' in short_name and len(short_name) > 45:
                short_name = short_name[:short_name.index('<') + 1] + '…>'
            elif len(short_name) > 45:
                short_name = short_name[:42] + '…'
            total_s = k['total_time_us'] / 1e6
            avg_s = k['avg_time_us'] / 1e6
            vgpr_str = f"{k['arch_vgpr']}"
            if k['accum_vgpr'] > 0:
                vgpr_str += f"+{k['accum_vgpr']}a"
            lds_str = f"{k['lds_bytes']:,}B" if k['lds_bytes'] > 0 else "—"
            occ_str = f"{k['occupancy_pct']:.0f}%"
            cu_cov = k['cu_coverage_pct']
            cu_str = f"{cu_cov:.0f}%"
            if cu_cov < 50:
                cu_str = f"**{cu_cov:.1f}%** ⚠"
            md.append(f"| `{short_name}` | {k['dispatch_count']:,} | {total_s:.2f}s | "
                      f"{_fmt_s(k['avg_time_us'])} | {k['workgroup_size']} | "
                      f"{k['max_grid_size']:,} | {vgpr_str} | {lds_str} | {occ_str} | {cu_str} |")

        # Highlight severe underutilization
        underutilized = [k for k in kernel_occ if k['cu_coverage_pct'] < 50]
        if underutilized:
            md.append("\n### CU Utilization Findings\n")
            for k in underutilized:
                short_name = k['name'].split('(')[0].strip()
                md.append(f"- **`{short_name}`**: Grid={k['max_grid_size']:,} threads → "
                          f"{k['waves_per_dispatch']} wave(s) across {k['num_cus']} CUs = "
                          f"**{k['cu_coverage_pct']:.1f}% CU coverage**. "
                          f"Each dispatch uses only {k['waves_per_dispatch']} of {k['num_cus']} CUs. "
                          f"With {k['dispatch_count']:,} dispatches totaling "
                          f"{k['total_time_us']/1e6:.1f}s, this is the primary utilization bottleneck. "
                          f"Batching multiple queries per dispatch would dramatically improve CU occupancy.")
        md.append("")

    # ── 8. HIP API Overhead ─────────────────────────────────────────────
    md.append("## 8. HIP API Overhead\n")
    hip_calls_flat: List[Tuple[str, float, int]] = []
    hw_dma_entries: List[Tuple[str, float, int]] = []  # hardware DMA (memcpy_memcpy etc.)
    for stage in gpu_data['stages']:
        for h in gpu_data['stages'].get(stage, {}).get('gpu_api_calls', []):
            if h['name'].startswith('memcpy_'):
                hw_dma_entries.append((h['name'], h['duration_us'] / 1e6, h['count']))
            else:
                hip_calls_flat.append((h['name'], h['duration_us'] / 1e6, h['count']))
    hip_calls_flat.sort(key=lambda x: -x[1])
    top_hip = hip_calls_flat[:10]
    if top_hip:
        md.append("![HIP API Overhead](hip_api_overhead.png)\n")
        md.append("| API Call | Total Time | Calls | Avg/Call |")
        md.append("|----------|-----------|-------|---------|")
        for name, t, cnt in top_hip:
            avg = t / cnt if cnt else 0
            md.append(f"| `{name}` | {t:.2f}s | {cnt:,} | {_fmt_s(avg * 1e6)} |")
        total_hip_time = sum(t for _, t, _ in hip_calls_flat)
        sync_time = next((t for n, t, _ in hip_calls_flat if n == 'hipDeviceSynchronize'), 0)
        real_overhead = total_hip_time - sync_time
        if gpu_kernel_total > 0:
            md.append(f"\n**Total HIP API time:** {total_hip_time:.1f}s "
                      f"(of which {sync_time:.1f}s is sync-wait overlapping kernel execution)  ")
            md.append(f"**Real HIP API overhead:** {real_overhead:.1f}s "
                      f"({real_overhead / gpu_kernel_total * 100:.1f}% of kernel time)")
        md.append("")

    # ── Synchronization & Overlap Analysis (subsection of HIP API) ─────
    gpu_api_all = extract_gpu_api_calls(gpu_data)
    gpu_kernels_all = extract_gpu_kernels(gpu_data)
    gpu_kernel_total_us = gpu_data['summary']['total_gpu_time_us']
    sync_analysis = analyze_sync_overlap(gpu_api_all, gpu_kernels_all, gpu_kernel_total_us)
    if sync_analysis:
        sa = sync_analysis
        md.append("### Synchronization & Overlap Analysis\n")
        md.append(f"`hipDeviceSynchronize` accounts for {sa['sync_time_us']/1e6:.1f}s "
                  f"({sa['sync_count']:,} calls). `hipLaunchKernel` dispatched "
                  f"{sa['user_kernel_count']:,} user kernels. GPU kernel execution totals "
                  f"{gpu_kernel_total:.1f}s ({sa['kernel_count']:,} dispatches including "
                  f"runtime-internal copies/fills).\n")
        if sa['dominant_kernel']:
            dk_name, dk_time, dk_count = sa['dominant_kernel']
            md.append(f"**Dominant kernel:** `{dk_name}` — {dk_time/1e6:.1f}s, "
                      f"{dk_count:,} dispatches\n")
        if sa['is_sync_waiting']:
            reasons = []
            if sa['sync_matches_launches']:
                reasons.append(f"sync count ({sa['sync_count']:,}) ≈ launch count ({sa['user_kernel_count']:,})")
            if sa['sync_approx_kernel_time']:
                reasons.append(f"sync time ({sa['sync_time_us']/1e6:.1f}s) ≈ kernel time ({gpu_kernel_total:.1f}s)")
            md.append(f"**Pattern detected: SYNCHRONOUS DISPATCH** — {'; '.join(reasons)}. "
                      f"Each kernel launch is immediately followed by `hipDeviceSynchronize`. "
                      f"The sync time is **not** additional overhead — it simply waits for "
                      f"the async kernel to complete.\n")
        md.append("| Category | Time | Calls | Note |")
        md.append("|----------|------|-------|------|")
        md.append(f"| Sync wait (overlapped with kernels) | {sa['overlap_us']/1e6:.1f}s | "
                  f"{sa['sync_count']:,} | Not extra overhead |")
        md.append(f"| Memory alloc/free | {sa['alloc_time_us']/1e6:.1f}s | "
                  f"{sa['alloc_count']:,} | hipMalloc + hipFree + hipHostMalloc + hipHostFree |")
        md.append(f"| Memory copy | {sa['memcpy_time_us']/1e6:.1f}s | "
                  f"{sa['memcpy_count']:,} | hipMemcpy + hipMemcpyAsync |")
        md.append(f"| Kernel launch | {sa['launch_time_us']/1e6:.1f}s | — | "
                  f"hipLaunchKernel + push/pop config |")
        md.append(f"| Memory set | {sa['memset_time_us']/1e6:.1f}s | — | hipMemset* |")
        md.append(f"| **Real HIP API overhead** | **{sa['real_api_overhead_us']/1e6:.1f}s** | — | "
                  f"Excluding sync overlap |")
        if gpu_kernel_total_us > 0:
            md.append(f"\n**Real overhead vs kernel time:** "
                      f"{sa['real_api_overhead_us'] / gpu_kernel_total_us * 100:.1f}%")
        md.append("")

    # ── 9. Host <-> Device Transfers ────────────────────────────────────
    md.append("## 9. Host \u2194 Device Transfers\n")
    # Collect transfers from both gpu_transfers (hardware-level) and
    # gpu_api_calls entries containing 'memcpy' (HIP API level)
    md_transfers: List[dict] = []
    for stage in gpu_data['stages']:
        for t in gpu_data['stages'].get(stage, {}).get('gpu_transfers', []):
            md_transfers.append(t)
        for a in gpu_data['stages'].get(stage, {}).get('gpu_api_calls', []):
            if 'memcpy' in a.get('name', '').lower():
                md_transfers.append(a)
    if md_transfers:
        md.append("| Operation | Total Time | Calls | Bytes | BW (GB/s) | Layer |")
        md.append("|-----------|-----------|-------|-------|-----------|-------|")
        for t in sorted(md_transfers, key=lambda x: -x.get('duration_us', 0)):
            dur = t.get('duration_us', 0)
            cnt = t.get('count', 0)
            b = t.get('bytes_total', 0)
            bw = b / (dur / 1e6) / 1e9 if dur > 0 and b > 0 else 0
            name = t.get('direction', t.get('name', '?'))
            layer = 'DMA' if name.startswith('memcpy_') else 'HIP API'
            md.append(f"| `{name}` | {_fmt_s(dur)} | {cnt:,} | {_fmt_bytes(b)} | {bw:.1f} | {layer} |")
        # Compute DMA bandwidth from hardware-level entries (those with actual byte counts)
        dma_entries = [t for t in md_transfers if t.get('bytes_total', 0) > 0]
        total_dma_bytes = sum(t.get('bytes_total', 0) for t in dma_entries)
        total_dma_time = sum(t.get('duration_us', 0) for t in dma_entries)
        total_api_time = sum(t.get('duration_us', 0) for t in md_transfers)
        if total_dma_bytes > 0:
            dma_bw = total_dma_bytes / (total_dma_time / 1e6) / 1e9 if total_dma_time > 0 else 0
            eff_bw = total_dma_bytes / (total_api_time / 1e6) / 1e9 if total_api_time > 0 else 0
            md.append(f"\n**Total transferred:** {_fmt_bytes(total_dma_bytes)}  ")
            md.append(f"**DMA bandwidth:** {dma_bw:.1f} GB/s (hardware transfer time: {_fmt_s(total_dma_time)})  ")
            md.append(f"**Effective bandwidth:** {eff_bw:.1f} GB/s (including HIP API overhead: {_fmt_s(total_api_time)})")
    else:
        md.append("No memory copy operations found in profiling data.\n")

    # ── 10. Function Comparison ─────────────────────────────────────────
    md.append("\n## 10. Function Comparison (CPU \u2192 GPU)\n")
    # Build function maps using only the top-level (outermost) function per
    # name.  trace_functions may list both parent and nested children; taking
    # the max duration per name selects the outermost inclusive measurement
    # so we don't double-count nested chains.
    def _top_fn_map(data: dict) -> dict:
        m: dict = {}
        for s in GRAPH_STAGES:
            for fn in data['stages'].get(s, {}).get('trace_functions', []):
                name = fn['name']
                if name not in m or fn['duration_us'] > m[name][0]:
                    m[name] = (fn['duration_us'], s)
        return m
    cpu_fn_map = _top_fn_map(cpu_data)
    gpu_fn_map = _top_fn_map(gpu_data)

    replaced = [(name, dur, stage) for name, (dur, stage) in cpu_fn_map.items()
                if name not in gpu_fn_map]
    replaced.sort(key=lambda x: -x[1])
    if replaced:
        md.append("### Functions replaced by GPU\n")
        md.append("| Function | CPU Time | Stage |")
        md.append("|----------|----------|-------|")
        for name, dur, stage in replaced[:10]:
            md.append(f"| `{name}` | {_fmt_s(dur)} | {stage} |")
        total_replaced = sum(d for _, d, _ in replaced)
        md.append(f"\n**Total CPU compute replaced:** {_fmt_s(total_replaced)}")

    new_fns = [(name, dur, stage) for name, (dur, stage) in gpu_fn_map.items()
               if name not in cpu_fn_map]
    new_fns.sort(key=lambda x: -x[1])
    if new_fns:
        md.append("\n### New functions in GPU mode\n")
        md.append("| Function | GPU Time | Stage |")
        md.append("|----------|----------|-------|")
        for name, dur, stage in new_fns[:10]:
            md.append(f"| `{name}` | {_fmt_s(dur)} | {stage} |")

    # ── 11. Memory Timeline ─────────────────────────────────────────────
    md.append("\n## 11. GPU Memory Timeline\n")
    if os.path.exists(os.path.join(out_dir, 'memory_timeline.png')):
        md.append("![Memory Timeline](memory_timeline.png)\n")
    else:
        md.append("Memory timeline graph not available.\n")

    # ── 12. Bottleneck Identification & Recommendations ─────────────────
    md.append("## 12. Bottleneck Identification & Recommendations\n")
    bottleneck = max(GRAPH_STAGES, key=lambda s: gpu_trace[s])
    bn_pct = gpu_trace[bottleneck] / gpu_total * 100 if gpu_total else 0
    md.append(f"### Primary Bottleneck: **{bottleneck.upper()}**\n")
    md.append(f"- Wall time: {gpu_trace[bottleneck]:.1f}s ({bn_pct:.1f}% of GPU-mode total)")
    md.append(f"- GPU kernel time: {gpu_kernel[bottleneck]:.1f}s")
    bn_overhead = gpu_trace[bottleneck] - gpu_kernel[bottleneck]
    if gpu_kernel[bottleneck] > 0:
        md.append(f"- Host overhead: {bn_overhead:.1f}s ({bn_overhead/gpu_trace[bottleneck]*100:.0f}% of stage wall time)")
    bn_speedup = cpu_trace[bottleneck] / gpu_trace[bottleneck] if gpu_trace[bottleneck] > 0 else 0
    md.append(f"- vs CPU: {bn_speedup:.2f}x {'faster' if bn_speedup >= 1 else 'slower'}")

    md.append("\n### Recommendations\n")

    # CU underutilization — the most actionable finding when present
    kernel_occ = gpu_data.get('kernel_occupancy', [])
    underutilized = [k for k in kernel_occ if k['cu_coverage_pct'] < 50]
    if underutilized:
        # Sort by total time to highlight the biggest offender first
        underutilized.sort(key=lambda k: -k['total_time_us'])
        md.append("**Primary optimization target: kernel batching**\n")
        for k in underutilized:
            short_name = k['name'].split('(')[0].strip()
            md.append(f"- **`{short_name}`** uses only {k['cu_coverage_pct']:.1f}% of CUs "
                      f"({k['waves_per_dispatch']} wave(s) on {k['num_cus']} CUs per dispatch). "
                      f"With {k['dispatch_count']:,} serial dispatches totaling "
                      f"{k['total_time_us']/1e6:.1f}s, batching multiple queries per launch "
                      f"could reduce kernel time by up to "
                      f"{min(k['num_cus'] // max(k['waves_per_dispatch'], 1), k['dispatch_count']):.0f}x.")
        md.append("")

    for s in GRAPH_STAGES:
        sp = cpu_trace[s] / gpu_trace[s] if gpu_trace[s] > 0 else 0
        if sp < 1:
            overhead = gpu_trace[s] - cpu_trace[s]
            md.append(f"- **{s.upper()}** regression: {1/sp:.1f}x slower (+{overhead:.1f}s)")
            if s == 'alignment' and gpu_kernel.get(s, 0) > 0:
                host_time = gpu_trace[s] - gpu_kernel[s]
                md.append(f"  - GPU kernel: {gpu_kernel[s]:.1f}s, Host overhead: {host_time:.1f}s ({host_time/gpu_trace[s]*100:.0f}%)")
                md.append("  - Consider batch-launching GPU alignment kernels to reduce per-call overhead")
                for hip_name, hip_t, hip_cnt in hip_calls_flat:
                    if hip_name in ('hipMalloc', 'hipFree', 'hipDeviceSynchronize') and hip_cnt > 1000:
                        md.append(f"  - `{hip_name}` called {hip_cnt:,} times ({hip_t:.1f}s) — pool allocation recommended")
                    elif hip_name in ('hipHostMalloc', 'hipHostFree') and hip_cnt > 0 and hip_t > 1.0:
                        avg_ms = hip_t / hip_cnt * 1000
                        md.append(f"  - `{hip_name}` called {hip_cnt:,} times ({hip_t:.1f}s, {avg_ms:.0f}ms/call) "
                                  f"— pre-allocate pinned buffers or use a pinned memory pool")
        elif sp > 1:
            md.append(f"- **{s.upper()}** speedup: {sp:.1f}x faster (GPU saves {cpu_trace[s] - gpu_trace[s]:.1f}s)")

    # Memory footprint findings
    cpu_rss_peak = gpu_mem.get('cpu_rss_peak_bytes', 0) if gpu_mem else 0
    cpu_rss_peak_cpu = cpu_mem.get('cpu_rss_peak_bytes', 0) if cpu_mem else 0
    if cpu_rss_peak > 0 and cpu_rss_peak_cpu > 0 and cpu_rss_peak > 2 * cpu_rss_peak_cpu:
        ratio = cpu_rss_peak / cpu_rss_peak_cpu
        md.append(f"- **Memory footprint:** GPU mode uses {_fmt_bytes(cpu_rss_peak)} CPU RSS "
                  f"vs {_fmt_bytes(cpu_rss_peak_cpu)} in CPU-only mode ({ratio:.1f}x increase). "
                  f"Reducing per-alignment allocations (hipMalloc/hipFree) and reusing "
                  f"host-side buffers would lower RSS.")

    if overall_speedup < 1:
        md.append(f"\n**Projected improvement (host overhead):** Eliminating {bottleneck.upper()} "
                  f"host overhead ({bn_overhead:.0f}s) would bring GPU total to ~{gpu_total - bn_overhead:.0f}s")
        # Add kernel batching projection if CU underutilization data is available
        if underutilized:
            worst = underutilized[0]
            max_batch = min(worst['num_cus'] // max(worst['waves_per_dispatch'], 1),
                           worst['dispatch_count'])
            if max_batch > 1:
                kernel_time_s = worst['total_time_us'] / 1e6
                batched_kernel_s = kernel_time_s / max_batch
                batched_total = gpu_total - kernel_time_s + batched_kernel_s
                md.append(f"\n**Projected improvement (kernel batching):** Batching `{worst['name'].split('(')[0].strip()}` "
                          f"to fill all {worst['num_cus']} CUs would reduce its {kernel_time_s:.1f}s kernel time "
                          f"to ~{batched_kernel_s:.1f}s, bringing the GPU total to ~{batched_total:.0f}s "
                          f"({cpu_total / batched_total:.1f}x vs CPU)")

    # ── 13. Output Files ────────────────────────────────────────────────
    md.append("\n## 13. Output Files\n")
    md.append("| File | Description |")
    md.append("|------|-------------|")
    md.append("| `analysis.json` | Structured profiling data |")
    md.append("| `trace.log` | Minimap2 trace timing output |")
    md.append("| `vtune/` | VTune raw profiling data |")
    md.append("| `rocprof/` | rocprofv3 kernel/HIP trace data |")
    md.append("| `logs/` | Tool run logs (vtune_run.log, rocprof_run_*.log) |")
    md.append("| `memory_timeline.png` | GPU/CPU memory usage over time |")

    md_text = '\n'.join(md) + '\n'
    report_path = os.path.join(out_dir, 'PROFILING_REPORT.md')
    with open(report_path, 'w') as f:
        f.write(md_text)
    print(f"Report: {report_path}")


# ═══════════════════════════════════════════════════════════════════════════
# CLI entry point
# ═══════════════════════════════════════════════════════════════════════════

def main():
    parser = argparse.ArgumentParser(
        description="Generate CPU vs GPU profiling comparison report",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument('cpu_analysis', type=Path,
                        help='Path to CPU-only analysis.json')
    parser.add_argument('gpu_analysis', type=Path,
                        help='Path to GPU analysis.json')
    parser.add_argument('--output-dir', '-o', type=str, default=None,
                        help='Directory for Markdown report and graphs (optional)')

    args = parser.parse_args()

    if not args.cpu_analysis.exists():
        print(f"Error: CPU analysis file not found: {args.cpu_analysis}", file=sys.stderr)
        sys.exit(1)
    if not args.gpu_analysis.exists():
        print(f"Error: GPU analysis file not found: {args.gpu_analysis}", file=sys.stderr)
        sys.exit(1)

    cpu_data = load_analysis(args.cpu_analysis)
    gpu_data = load_analysis(args.gpu_analysis)

    # Always print text comparison to stdout
    print_comparison(cpu_data, gpu_data, args.cpu_analysis, args.gpu_analysis)

    # Generate graphs + Markdown report if output dir specified
    if args.output_dir:
        os.makedirs(args.output_dir, exist_ok=True)
        generate_graphs(cpu_data, gpu_data, args.output_dir)
        generate_markdown_report(cpu_data, gpu_data, args.output_dir)
        graph_files = [f for f in sorted(os.listdir(args.output_dir)) if f.endswith('.png')]
        print(f"\nGenerated {len(graph_files)} graphs:")
        for f in graph_files:
            print(f"  {f}")


if __name__ == '__main__':
    main()
